# Generated by Django 3.2.9 on 2021-12-30 08:18

import cloudinary.models
from django.db import migrations, models
# Generated by Django 3.2.9 on 2022-01-06 05:06

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_reg_no', models.CharField(max_length=30)),
                ('institution_name', models.CharField(max_length=40)),
                ('location_name', models.CharField(max_length=20)),
                ('location_address', models.CharField(max_length=20)),
                ('institution_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_reg_no', models.CharField(max_length=30)),
                ('learner_first_name', models.CharField(max_length=10)),
                ('learner_second_name', models.CharField(blank=True, max_length=10)),
                ('learner_last_name', models.CharField(max_length=10)),
                ('course_taken', models.CharField(max_length=30)),
                ('date_enrolled', models.DateTimeField()),
                ('date_completed', models.DateTimeField()),
                ('grade_attained', models.CharField(max_length=20)),
                ('certificate_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('institution', models.ManyToManyField(to='api.Institution')),
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('company_name', models.CharField(max_length=50)),
                ('about', models.TextField(blank=True, max_length=1000)),
                ('company_tel_number', models.IntegerField()),
                ('company_email', models.EmailField(max_length=254)),
                ('company_reg_number', models.CharField(max_length=20)),
                ('joined_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
