# Generated by Django 3.2.9 on 2022-01-06 05:06

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('company_name', models.CharField(max_length=50)),
                ('about', models.TextField(blank=True, max_length=1000)),
                ('company_tel_number', models.IntegerField()),
                ('company_email', models.EmailField(max_length=254)),
                ('company_reg_number', models.CharField(max_length=20)),
                ('joined_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
