# Generated by Django 3.2.9 on 2021-12-30 08:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_reg_no', models.CharField(max_length=30)),
                ('institution_name', models.CharField(max_length=40)),
                ('location_name', models.CharField(max_length=20)),
                ('location_address', models.CharField(max_length=20)),
                ('institution_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_reg_no', models.CharField(max_length=30)),
                ('learner_first_name', models.CharField(max_length=10)),
                ('learner_second_name', models.CharField(blank=True, max_length=10)),
                ('learner_last_name', models.CharField(max_length=10)),
                ('course_taken', models.CharField(max_length=30)),
                ('date_enrolled', models.DateTimeField()),
                ('date_completed', models.DateTimeField()),
                ('grade_attained', models.CharField(max_length=20)),
                ('certificate_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('institution', models.ManyToManyField(to='api.Institution')),
            ],
        ),
    ]
