# Generated by Django 3.2.9 on 2022-01-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='institution',
        ),
        migrations.AddField(
            model_name='learner',
            name='institution',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.institution'),
            preserve_default=False,
        ),
    ]
