# Generated by Django 3.2.9 on 2022-01-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220113_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='reg_number',
            field=models.CharField(max_length=20),
        ),
    ]
